### ISSUE TITLE
感谢楼主的开源，选择器样式很漂亮，功能也很棒，支持很多自定义UI，现在有个小BUG反馈一下

### ISSUE THREAD

**Issue by RookieExaminer** [loperSeven/DateTimePicker#11]
设置时间选择只选择年份和月份，然后最大值为当前时间戳2021.01.09...，
然后滑动滚轮至2020.12，然后再滑动滚轮到2021年（月份不选择，显示的默认为1月），
然后点击确定后，回调时间为2021年12月

代码：

  val displayList = mutableListOf<Int>()
        displayList.add(DateTimeConfig.YEAR)
        displayList.add(DateTimeConfig.MONTH)
        val model = CardDatePickerDialog.STACK
        val maxDate = TimeUtils.getNowMills()
        CardDatePickerDialog.builder(this)
            .setTitle("日期选择")
            .setDisplayType(displayList)
            .setBackGroundModel(model)
            .showBackNow(false)
            .setMaxTime(maxDate)
            .setWrapSelectorWheel(false)
            .setThemeColor(Color.parseColor("#4169E1"))
            .showDateLabel(true)
            .showFocusDateInfo(false)
            .setOnChoose("选择") {
                tvTimeSelect.text = StringUtils.conversionTime(it, "yyyy-MM")
            }
            .setOnCancel("关闭") {
            }.build().show()

**Comment by loperSeven** [comment]
> 设置时间选择只选择年份和月份，然后最大值为当前时间戳2021.01.09...，
> 然后滑动滚轮至2020.12，然后再滑动滚轮到2021年（月份不选择，显示的默认为1月），
> 然后点击确定后，回调时间为2021年12月
> 
> 代码：
> 
> val displayList = mutableListOf()
> displayList.add(DateTimeConfig.YEAR)
> displayList.add(DateTimeConfig.MONTH)
> val model = CardDatePickerDialog.STACK
> val maxDate = TimeUtils.getNowMills()
> CardDatePickerDialog.builder(this)
> .setTitle("日期选择")
> .setDisplayType(displayList)
> .setBackGroundModel(model)
> .showBackNow(false)
> .setMaxTime(maxDate)
> .setWrapSelectorWheel(false)
> .setThemeColor(Color.parseColor("#4169E1"))
> .showDateLabel(true)
> .showFocusDateInfo(false)
> .setOnChoose("选择") {
> tvTimeSelect.text = StringUtils.conversionTime(it, "yyyy-MM")
> }
> .setOnCancel("关闭") {
> }.build().show()

0.3.2 已修复
