### ISSUE TITLE
我是java的0.3.0在setOnChoose时没有找到CardDatePickerDialog.OnChooseListener()

### ISSUE THREAD

**Issue by TheorayVic** [loperSeven/DateTimePicker#13]
我是java的0.3.0在setOnChoose时没有找到CardDatePickerDialog.OnChooseListener()
然后您给的例子里面是这些 我看不懂
/**
*示例
*setOnChoose("确定")
*setOnChoose{millisecond->}
*setOnChoose("确定"){millisecond->}
*/
fun setOnChoose(text: String = "确定", listener: ((Long) -> Unit)? = null)

所以一直无法setOnChoose，
.setOnChoose("选择",)
这里第二个参数用java是怎么写的？

感谢

**Comment by loperSeven** [comment]
> 我是java的0.3.0在setOnChoose时没有找到CardDatePickerDialog.OnChooseListener()
> 然后您给的例子里面是这些 我看不懂
> /**
> *示例
> *setOnChoose("确定")
> *setOnChoose{millisecond->}
> *setOnChoose("确定"){millisecond->}
> */
> fun setOnChoose(text: String = "确定", listener: ((Long) -> Unit)? = null)
> 
> 所以一直无法setOnChoose，
> .setOnChoose("选择",)
> 这里第二个参数用java是怎么写的？
> 
> 感谢

[wiki](https://github.com/loperSeven/DateTimePicker/wiki/CardDatePickerDialog-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)里面有针对java的示例，可以参考一下

**Comment by TheorayVic** [comment]
new CardDatePickerDialog.Builder(this)
                .setTitle("SET MAX DATE")
                .setOnChoose("确定", new Function1<Long, kotlin.Unit>() {
                    @Override
                    public Unit invoke(Long aLong) {
                        //aLong  = millisecond
                        return null;
                    }
                }).build().show();
                
   这样写进去的时候、kotlin.Unit的kotlin是Cannot resolve symbol ‘kotlin’
   
   然后invoke方法的返回值Unit也是Cannot resolve symbol ‘Unit’

**Comment by loperSeven** [comment]
> new CardDatePickerDialog.Builder(this)
> .setTitle("SET MAX DATE")
> .setOnChoose("确定", new Function1<Long, kotlin.Unit>() {
> @override
> public Unit invoke(Long aLong) {
> //aLong = millisecond
> return null;
> }
> }).build().show();
> 
> 这样写进去的时候、kotlin.Unit的kotlin是Cannot resolve symbol ‘kotlin’
> 
> 然后invoke方法的返回值Unit也是Cannot resolve symbol ‘Unit’

需要导入 kotlin包
