### ISSUE TITLE
可以支持多语言吗

### ISSUE THREAD

**Issue by D-zy** [loperSeven/DateTimePicker#14]
需要多语言

**Comment by loperSeven** [comment]
> 需要多语言

datetimePicker 的所有文字都是可以配置的
dialog里面 标题，取消，确定按钮文字都是可以配置的  唯有 标题下面日期提示展示/以及底部回到当前定制性较强不支持动态配置。是需要这一块儿支持多语言吗？

**Comment by D-zy** [comment]
是的，博主有时间可以优化下哈，不然只能下载源码修改了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;LOPER7&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月20日(星期三) 下午5:18
收件人:&nbsp;&quot;loperSeven/DateTimePicker&quot;<DateTimePicker@noreply.github.com&gt;;
抄送:&nbsp;&quot;D-zy&quot;<1262481149@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [loperSeven/DateTimePicker] 可以支持多语言吗 (#14)

**Comment by loperSeven** [comment]
> 是的，博主有时间可以优化下哈，不然只能下载源码修改了------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;LOPER7&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月20日(星期三) 下午5:18 收件人:&nbsp;&quot;loperSeven/DateTimePicker&quot;<DateTimePicker@noreply.github.com&gt;; 抄送:&nbsp;&quot;D-zy&quot;<1262481149@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [loperSeven/DateTimePicker] 可以支持多语言吗 (#14)

不需要下载源码改，自定义dialog就可以了。

**Comment by loperSeven** [comment]
> > 是的，博主有时间可以优化下哈，不然只能下载源码修改了------------------ 原始邮件 ------------------ 发件人: "LOPER7"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2021年1月20日(星期三) 下午5:18 收件人: "loperSeven/DateTimePicker"<[DateTimePicker@noreply.github.com](mailto:DateTimePicker@noreply.github.com)>; 抄送: "D-zy"<[1262481149@qq.com](mailto:1262481149@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [loperSeven/DateTimePicker] 可以支持多语言吗 (#14)
> 
> 不需要下载源码改，自定义dialog就可以了。
