### ISSUE TITLE
修改滚动样式

### ISSUE THREAD

**Issue by wvisible** [loperSeven/DateTimePicker#16]
感谢作者开源的库，非常好用和自定义，但是遇到一个问题，可以修改滚动的样式跟Android自带的NumberPicker一样的滚动样式吗？上下一起滚动

**Comment by loperSeven** [comment]
> 感谢作者开源的库，非常好用和自定义，但是遇到一个问题，可以修改滚动的样式跟Android自带的NumberPicker一样的滚动样式吗？上下一起滚动

上下一起滚动是指？

**Comment by wvisible** [comment]
就是类似于系统的NumberPicker，中间的数字跟上下的一起滚动，现在是感觉上下是在中间的下面滚动的？

**Comment by loperSeven** [comment]
> 就是类似于系统的NumberPicker，中间的数字跟上下的一起滚动，现在是感觉上下是在中间的下面滚动的

目前不行，年后准备recode一下number picker ，到时候看能不能让滑动效果好一点

**Comment by luyun181** [comment]
大哥，这个滚动样式修改了吗？
