### ISSUE TITLE
怎么设置不循环滚动

### ISSUE THREAD

**Issue by cczhr** [loperSeven/DateTimePicker#24]
DateTimeController  把wrapSelectorWheel设为false  滚轮上方还是有最大值

**Comment by loperSeven** [comment]
我在demo上跑了一遍，没有复现这样的问题，你可以下载demo设置最大值和最小值尝试，需要注意的是，诸如年份变动之类的动作如果触发了最大最小值约束，由于重置了后位单位的值，所以即使设置了禁止循环滚动，但依旧会在上方显示最大值，但此时是无法向上滚动的。

**Comment by cczhr** [comment]
我把你的NumberPicker 改用回 https://github.com/ShawnLin013/NumberPicker “由于重置了后位单位的值，所以即使设置了禁止循环滚动，但依旧会在上方显示最大值” 这个问题就解决了

**Comment by cczhr** [comment]
“诸如年份变动之类的动作如果触发了最大最小值约束，由于重置了后位单位的值，所以即使设置了禁止循环滚动，但依旧会在上方显示最大值，但此时是无法向上滚动的。” 禁止循环滚动的情况下 感觉没必要上方显示最大值。

**Comment by loperSeven** [comment]
&#x1F44D;
我去更新一下numberpicker库
