### ISSUE TITLE
设置最小时间范围后， 滑动会出现异常显示

### ISSUE THREAD

**Issue by fugang123** [loperSeven/DateTimePicker#26]
![image](https://user-images.githubusercontent.com/18046345/128975570-2e287600-f13d-4f6d-8d1a-9060846cb8a8.png)

**Comment by fugang123** [comment]
![image](https://user-images.githubusercontent.com/18046345/128975620-cb011e95-4674-413b-8a21-fe9dad336bfc.png)
显示出来滑动不了

**Comment by loperSeven** [comment]
之前一直在忙项目没来得及处理  现已修复
