### ISSUE TITLE
是否考虑支持下时间显示国际化呢

### ISSUE THREAD

**Issue by githeer** [loperSeven/DateTimePicker#28]
希望支持日期格式国际化，月份什么的

**Comment by loperSeven** [comment]
> 希望支持日期格式国际化，月份什么的
国际化主要是年月日的顺序和月份用英文显示，其他的没有什么变动，通过DateTimePicker提供的自定义layout的方法加上一个对月份的格式化就可以实现，由于月份用英文的方式显示会特别长，所以导致屏幕无法横向塞下年月日时分秒，这个是需要考虑的。

**Comment by loperSeven** [comment]
0.3.4 已支持
