### ISSUE TITLE
做的很漂亮，感谢

### ISSUE THREAD

**Issue by GXSZone** [loperSeven/DateTimePicker#3]
能否加这个  `月日（周）-时-分` 格式
在`月日（周）`这里今天显示今天，明天显示明天，其余按标准格式显示

**Comment by loperSeven** [comment]
非常棒的建议，之前只考虑到一种展示方式，代码全在一块拓展较难，现在源码已经做了以下改动：

- 新增DateTimeController逻辑控制器，以支持UI 100% 自定义
- 重构DateTimePicker，抽离逻辑至DateTimeController,自身仅控制UI
- 抽离常量至DateTimeConfig
- 抽离像素单位转换至ContextExt拓展

在现有结构下，完全允许自定义组件样式，只需将申明好的
```kotlin
com.loper7.date_time_picker.number_picker.NumberPicker
```
传入DateTimeController逻辑控制器即可，比如[DateTimePicker](https://github.com/loperSeven/DateTimePicker/blob/master/date_time_picker/src/main/java/com/loper7/date_time_picker/DateTimePicker.kt)类，后续我会再编写一些常用的日期/时间样式满足大部分使用场景，如果你已经在项目中使用并迫切希望实现，你可以下载最新的代码至本地，然后如我上述所说的自定义UI就可以了。

**Comment by loperSeven** [comment]
[0.2.0](https://github.com/loperSeven/DateTimePicker/releases/tag/0.2.0)已更新，可参照[DateTimePicker](https://github.com/loperSeven/DateTimePicker/blob/master/date_time_picker/src/main/java/com/loper7/date_time_picker/DateTimePicker.kt)自定义UI

**Comment by GXSZone** [comment]
谢谢

**Comment by GXSZone** [comment]
@loperSeven 谢谢
