### ISSUE TITLE
设置默认时间有BUG

### ISSUE THREAD

**Issue by hzzzJ** [loperSeven/DateTimePicker#34]
铁汁，设置默认时间也有BUG呀

**Comment by loperSeven** [comment]
有什么bug  前段时间有点忙  今天开始刚好慢慢闲下来了

**Comment by hzzzJ** [comment]
> 有什么bug 每天前段时间有点忙开始刚好慢慢下来了

CardDatePickerDialog设置默认时间不生效，从mOnDateTimeChangedListener?.invoke(millisecond)拿到的时间直接塞到setDefaultTime里面也不生效

**Comment by loperSeven** [comment]
是用的 0.3.4吗
