### ISSUE TITLE
之前没更新NumberPicker没更新之前的版本那种翻动动画没了

### ISSUE THREAD

**Issue by GXSZone** [loperSeven/DateTimePicker#37]
README演示图的那种滚动动画干净利落很喜欢，并且字体是加粗

**Comment by GXSZone** [comment]
那种滚动动画还会加上去吗 @loperSeven

**Comment by loperSeven** [comment]
我试试

**Comment by loperSeven** [comment]
> 那种滚动动画还会加上去吗 @loperSeven
之前的滚动动画回不去了，如果比较执着于之前的动画的话，可以直接使用之前的版本（如果可以接受#24问题的话）~
然后这个版本新增了字体加粗属性
