### ISSUE TITLE
建议发布版本时把接口注释加上

### ISSUE THREAD

**Issue by bihailantian** [loperSeven/DateTimePicker#38]
使用的版本是：implementation 'com.github.loperSeven:DateTimePicker:0.4.1'
在AS里面的鼠标放到接口上都没有API接口注释，点进源码也是没有注释，建议发布版本时把接口注释加上。

**Comment by loperSeven** [comment]
picker 和 dialog 对外提供的方法或者构建参数都是有注释的噢，是看到哪里没有注释可以截图或者贴出来看看吗
