### ISSUE TITLE
Java 调用setMinTime/setMaxTime/setThemeColor时报Ambiguous method call

### ISSUE THREAD

**Issue by carlgik4** [loperSeven/DateTimePicker#4]
Ambiguous method call. Both
setMinTime(long)
in Builder and
setMinTime(long)
in Builder match

<img width="465" alt="Screenshot 2020-09-20 at 17 30 32" src="https://user-images.githubusercontent.com/544929/93708211-03ab9080-fb67-11ea-8d78-1f86adce1e93.png">

**Comment by loperSeven** [comment]
kotlin在java中默认是非public的，需要给方法注解@JvmField才可以开放给java调用。
感谢你的反馈，下个版本将会支持java使用
