### ISSUE TITLE
setBackGroundModel设置无效，无论设置何值，显示均是铺满屏幕宽度的白底直角

### ISSUE THREAD

**Issue by lch2014a** [loperSeven/DateTimePicker#44]
使用的是 com.google.android.material:material:1.3.0

**Comment by loperSeven** [comment]
> 使用的是 com.google.android.material:material:1.3.0

我在demo里一切正常，可以尝试跑demo试试，看是android版本导致还是其他原因，方便排查

**Comment by lch2014a** [comment]
> > 使用的是 com.google.android.material:material:1.3.0
> 
> 我在demo里一切正常，可以尝试跑demo试试，看是android版本导致还是其他原因，方便排查

<style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
把主题换成MaterialComponents就可以复现了

**Comment by loperSeven** [comment]
> > > 使用的是 com.google.android.material:material:1.3.0
> > 
> > 
> > 我在demo里一切正常，可以尝试跑demo试试，看是android版本导致还是其他原因，方便排查
> 
> <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar"> 把主题换成MaterialComponents就可以复现了

好，下个版本修复
