### ISSUE TITLE
NumberPicker设置np_textSize，np_selectedTextSize并不会生效

### ISSUE THREAD

**Issue by liyuhaolol** [loperSeven/DateTimePicker#48]
感觉文字大小会统一被DateTimePicker管理，但是默认的效果，textSize会自动比selectedTextSize小一点，我想自定义这个效果，但是发现没法通过xml设置实现

**Comment by loperSeven** [comment]
0.5.3已处理，datetimepicker xml 新增设置选中文字与未选中文字大小，若不设置，则不会覆盖在自定义xml中设置的numberPicker文字大小
