### ISSUE TITLE
可以不要循环滚动吗

### ISSUE THREAD

**Issue by StarAndRainbow** [loperSeven/DateTimePicker#5]
你好，可以指导一下，如果不想循环滚动，在那里入手进行修改吗

**Comment by loperSeven** [comment]
已新增如下方法
```
 /**
     * 设置是否Picker循环滚动
     * @param types 需要设置的Picker类型（DateTimeConfig-> YEAR,MONTH,DAY,HOUR,MIN,SECOND）
     * @param wrapSelector 是否循环滚动
     */
 fun setWrapSelectorWheel(types: MutableList<Int>?, wrapSelector: Boolean) 
 fun setWrapSelectorWheel(vararg types: Int, wrapSelector: Boolean) 
 fun setWrapSelectorWheel(wrapSelector: Boolean)
```
你可以下载源码体验和帮助我测试，如果成功解决了你的问题或仍有其他问题，可以在这条issues下反馈给我。待功能确认完成后将更新在未来版本 0.2.1 上。

**Comment by StarAndRainbow** [comment]
好的，放到项目中，可以使用。暂时没发现问题，发现问题再反馈，谢谢了。

另外我觉得setDisplayType，这个方法里面的判断可以加上else

`
 /**
     * 设置显示类型
     * @param types
     */
    fun setDisplayType(types: IntArray?) {
        if (types == null || types.isEmpty()) return
        displayType = types

        if (!displayType.contains(YEAR)) {
            mYearSpinner.visibility = View.GONE
        }else{
            mYearSpinner.visibility = View.VISIBLE
        }

        if (!displayType.contains(MONTH)) {
            mMonthSpinner.visibility = View.GONE
        }else{
            mMonthSpinner.visibility = View.VISIBLE
        }

        if (!displayType.contains(DAY)) {
            mDaySpinner.visibility = View.GONE
        }else{
            mDaySpinner.visibility = View.VISIBLE
        }

        if (!displayType.contains(HOUR)) {
            mHourSpinner.visibility = View.GONE
        }else{
            mHourSpinner.visibility = View.VISIBLE
        }

        if (!displayType.contains(MIN)) {
            mMinuteSpinner.visibility = View.GONE
        }else{
            mMinuteSpinner.visibility = View.VISIBLE
        }


        if (!displayType.contains(SECOND)) {
            mSecondSpinner.visibility = View.GONE
        }else{
            mSecondSpinner.visibility = View.VISIBLE
        }
    }`

需求就是

用户可以根据年-月-日，或者年-月进行筛选数据。

这时候，用户就会切换不同的显示类型

**Comment by loperSeven** [comment]
确实是，之前没有考虑到这样的场景，非常不错的建议
