### ISSUE TITLE
国际化的locale是不是有问题？

### ISSUE THREAD

**Issue by HeJingWei** [loperSeven/DateTimePicker#50]
在 DateTimeConfig单例中，DateFormatSybols传入的应该是Locale.getDefault()而不是Locale.US吧？不然所有都是英文的月份了

**Comment by HeJingWei** [comment]
我将缩写的月份显示改为了 DateFormatSymbols(Locale.getDefault()).shortMonths.toList()[value - 1]   不确认是否所有地区的月份缩写都是截取前三位

**Comment by loperSeven** [comment]
目前没有考虑那么多，本身来说阿拉伯数字本就全球通用，只是有些地区对年月日的排版方式习惯有不同，所以之前有位老哥提了个国际化issue的时候就只考虑了比较广泛的排版方式，本身dateTimePicker是支持自定义view的，所以其实年月日时分秒想怎么排都可以很轻松的实现，日期显示的格式化也可以通过设置 format 来处理。
