### ISSUE TITLE
有一个设置了最大值、最小值的小BUG

### ISSUE THREAD

**Issue by HeJingWei** [loperSeven/DateTimePicker#51]
如图，我设置了一个max和min，但是当我选择2022-10-29时，我只切换年份到2022，这时的月份是到1月了，但是日期依然是29号
![1643163989389](https://user-images.githubusercontent.com/16362351/151094630-d2d7638c-ecae-45a7-a254-45c7bc75bccf.jpg)

![1643163989381](https://user-images.githubusercontent.com/16362351/151094625-2d3aaf62-1475-4b9c-9ef1-9ff0a9f3c02d.jpg)

![1643163989368](https://user-images.githubusercontent.com/16362351/151094615-99b64889-ee76-4fae-91d4-ff2774aef5c3.jpg)

**Comment by loperSeven** [comment]
是下载最新demo编译的apk吗

**Comment by HeJingWei** [comment]
是下载的最新的代码编译的，就是日期会有这个问题，跟我上述的操作一样的

**Comment by loperSeven** [comment]
确实有这个问题  导致这个问题的原因感觉是numberpicker滑动监听有时候失效了，下个版本处理

**Comment by loperSeven** [comment]
确实有这个问题  我处理了  着急用的话可以先以module的方式导入使用

**Comment by HeJingWei** [comment]
thanks
