### ISSUE TITLE
你好，请问CardDatePickerDialog可以设置时间选择器宽高和文字大小吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [loperSeven/DateTimePicker#58]
默认的在这边的机器上比例不大协调

![微信图片_20220606113416](https://user-images.githubusercontent.com/54784104/172090236-27c68551-1d45-48be-a35a-802f6b32133a.jpg)

**Comment by loperSeven** [comment]
![image](https://user-images.githubusercontent.com/20430552/172511155-1e4d004e-6b3a-4526-b71a-dabb041b67ee.png)

**Comment by SaltedFish-Extreme** [comment]
> 可以的 看文档 不过 CardDatePickerDialog ui定制性太强，要契合自己项目的UI还是建议自己布局的好

但是我发现继承time picker布局自定义也没法调整宽高和比例，最后只能用[TimePickerDialog](https://github.com/JZXiang/TimePickerDialog)了

**Comment by loperSeven** [comment]
[自定义你的DateTimePicker](https://github.com/loperSeven/DateTimePicker/wiki/DateTimePicker-%E8%87%AA%E5%AE%9A%E4%B9%89) 看看这个，宽高比例位置想怎么搞就怎么搞

**Comment by SaltedFish-Extreme** [comment]
> [自定义你的DateTimePicker](https://github.com/loperSeven/DateTimePicker/wiki/DateTimePicker-%E8%87%AA%E5%AE%9A%E4%B9%89) 看看这个，宽高比例位置想怎么搞就怎么搞

有点不大会整，整不出来最后用了公司原先的库和自定义类了😂，就是这样的效果，一个底部dialog
![image](https://user-images.githubusercontent.com/54784104/172549844-1de7d998-f2c8-4398-b6f9-a8235f3b9e7f.png)
