### ISSUE TITLE
默认时间天数显示有误

### ISSUE THREAD

**Issue by Aatattoo** [loperSeven/DateTimePicker#61]
java项目导入该库，设置默认时间，最小时间和最大时间
最小时间和最大时间都是预期值
只有默认时间有一点问题，年-月-日 ：分
中的日显示的不是设置的时间，而是默认的日期
例如 当前时间 是 2022-6-30 12：12 
设置成 2022-7-3 12 ：12
但是显示的是 2022-7-30 12：12

我在该项目的demo里测试，默认时间设置显示的是没有问题的，

请问是因为我的原生项目是java引入该库导致的问题，这个问题有什么处理的思路吗

**Comment by loperSeven** [comment]
这个你要看你引入的版本，之前有个版本存在这个问题，demo内没问题应该是demo内是最新的版本

**Comment by loperSeven** [comment]
当前版本0.5.8

**Comment by Aatattoo** [comment]
感谢大大
