### ISSUE TITLE
NumberPicker如何隐藏分割线

### ISSUE THREAD

**Issue by linxiangcheer** [loperSeven/DateTimePicker#62]
app:np_divider="@null"
        app:np_dividerColor="@color/transparent"
        app:np_dividerThickness="0dp"

0.5.8版本，以上设置都不能隐藏分割线
在0.4.1可以通过app:np_dividerThickness=0dp隐藏

**Comment by linxiangcheer** [comment]
补充：可以通过getPicker(0)?.setDividerColorResource(R.color.transparent)隐藏掉 “年份”上下的分割线，但月、日、时、分、秒上下的分割线依旧在

**Comment by loperSeven** [comment]
目前没有，下个版本加上

**Comment by linxiangcheer** [comment]
了解，大佬加油

**Comment by loperSeven** [comment]
关于NumberPicker 的属性可以查阅 [NumberPicker](https://github.com/ShawnLin013/NumberPicker )，分割线颜色的设置新版本调整为了np_dividerColor

**Comment by alienzh** [comment]
np_dividerThickness 设置成 0dp 了，还是显示分割线
