### ISSUE TITLE
找不到design_bottom_sheet

### ISSUE THREAD

**Issue by ylmyg** [loperSeven/DateTimePicker#63]
val bottomSheet = delegate.findViewById<FrameLayout>(R.id.design_bottom_sheet)
我导入了你的包，发现运行的时候报错R.id.design_bottom_sheet找不到，请问此id是怎么来的呢

**Comment by loperSeven** [comment]
你的 material:material 版本是多少

**Comment by ylmyg** [comment]
我直接导入你的包。和你版本的一样的。1.5.0，我的主moudle还需要添加material:material 么   ？

**Comment by loperSeven** [comment]
你可以试试

**Comment by ylmyg** [comment]
加了也不行，有个问题想请教，我想通过一个按钮点击触发，使时间选择器年自动滚到下一年，我找了所有的方法，不知道怎么改，作者能指点下么

**Comment by zhouclcode** [comment]
可以试试
mBeginPickerDialog?.findViewById<DateTimePicker>(R.id.dateTimePicker)?.setDefaultMillisecond(beginTime.time)
