### ISSUE TITLE
app:np_selectedTextColor="@color/colorTextRed"无效果

### ISSUE THREAD

**Issue by LGYG** [loperSeven/DateTimePicker#65]
<com.loper7.date_time_picker.number_picker.NumberPicker
            android:layout_width="60dp"
            android:layout_height="wrap_content"
            android:tag="np_datetime_year"
            app:np_selectedTextColor="@color/colorTextRed"
            app:np_dividerColor="#00ffffff"
            app:np_dividerThickness="0.6dp"
            app:np_height="184dp"
            app:np_wheelItemCount="3"
            app:np_textColor="@color/colorTextRed"
            />

真机上运行，选中的字体没变颜色

**Comment by loperSeven** [comment]
需要看在代码里面有没有覆盖掉设置的颜色
