### ISSUE TITLE
设置最极值的问题

### ISSUE THREAD

**Issue by op123355569** [loperSeven/DateTimePicker#66]
设置最极值的问题，测试步骤：
1. 打开Demo，选择【CardDatePickerDialog】
2. 设置最大值（不做其他操作，直接取当前时间）
3. 过几秒，保证当前时间大于最大值
4. 点击【Show Dialog】
5. 如果不进行滑动，展示的时间为当前时间（大于最大时间），并且点击【选择】的话也会返回当前时间，这样结果会超过最大值
6. 如果进行滑动的话，则没有该问题

最小值的操作步骤类似

**Comment by loperSeven** [comment]
0.6.0 已修复
