### ISSUE TITLE
lable颜色和字体大佬

### ISSUE THREAD

**Issue by TSsimeon** [loperSeven/DateTimePicker#68]
大佬有没有计划支持lable颜色自定义和字体大小呢？或者说有什么别的方法没呢。现在，麻烦了

**Comment by loperSeven** [comment]
[自定义选择器UI](https://github.com/loperSeven/DateTimePicker/wiki/DateTimePicker-%E8%87%AA%E5%AE%9A%E4%B9%89)想怎么搞就怎么搞

**Comment by TSsimeon** [comment]
> [自定义选择器UI](https://github.com/loperSeven/DateTimePicker/wiki/DateTimePicker-%E8%87%AA%E5%AE%9A%E4%B9%89)想怎么搞就怎么搞

我的理解是自定义ui器改不到我的需求，我看了一下源码，文本显示和标签是同一个控件，所以无法分别设置。您看我的理解对吗

**Comment by loperSeven** [comment]
噢 label是指 年月日时分这样的文字  那确实不支持

**Comment by TSsimeon** [comment]
> 噢 label是指 年月日时分这样的文字 那确实不支持

好的。谢谢大佬。只能自己改一下源码了。

**Comment by loperSeven** [comment]
实现方式的话可以考虑用 SpannableString 来做，这个需求近期内应该不会考虑增加

**Comment by TSsimeon** [comment]
> 

嗯嗯我就是这样想的。就改一下而已。
