### ISSUE TITLE
分钟能自己设置数值吗

### ISSUE THREAD

**Issue by taozhixiang** [loperSeven/DateTimePicker#72]
只想保留00,15,30,45这样。怎么自己设置呢

**Comment by loperSeven** [comment]
这个暂不支持  只能自己想办法实现

**Comment by luyun181** [comment]
> 只想保留00,15,30,45这样。怎么自己设置呢

大哥。找个方法了吗

**Comment by loper7** [comment]
参考 [issues22 ](https://github.com/loper7/DateTimePicker/issues/22)，目前看来这个需求并不普遍，可以自行修改源码实现，或者自定义DateTimeController，将源码内DateTimeController代码复制并做相应改动，然后使用DateTimePicker.bindController 替换掉默认的DateTimeController
