### ISSUE TITLE
可以开放滚轮自定义布局吗，minTargetSdk可以兼容到19吗

### ISSUE THREAD

**Issue by twirain** [loperSeven/DateTimePicker#8]

**Comment by loperSeven** [comment]
1、滚轮自定义布局是指具体的某一个numberPicker吗？实例内的picker是由6个nuberPicker组成的，目前是可以支持自定义布局的，但是布局内必须有一个或多个numberPicker。numberPicker本身不支持再自定义。
2、minTargetSdk可以兼容到19，但考虑到2020年马上结束了，5.0及以下的机型市场占有率极低且性能有限，加上库内使用了BottomSheetDialog，所以暂不考虑兼容到19。如果你有兼容到19的需求，可以下载代码手动导入并更改minSdkVersion
