### ISSUE TITLE
添加时间间隔设定

### ISSUE THREAD

**Issue by LuXiaoQiang** [loperSeven/DateTimePicker#86]
能否添加指定分钟间隔选择，比如指定时间间隔分钟数是5分钟，那选择器的分钟展示格式是：XX时5分 XX时10分 XX时15分 XX时20分..XX时55分

**Comment by loper7** [comment]
参考[这条issue](https://github.com/loper7/DateTimePicker/issues/22)，里面有设定时间间隔

**Comment by LxzBUG** [comment]
我也想做这个，不要时间日期的，只要时长，比如1小时5分，2小时45分，然后获取这个时长😂😂 不知道怎么做 @loper7

**Comment by loper7** [comment]
这种不属于时间选择器呀，用两个RecyclerView 不就搞定了吗

**Comment by loper7** [comment]
> 我也想做这个，不要时间日期的，只要时长，比如1小时5分，2小时45分，然后获取这个时长😂😂 不知道怎么做 @loper7

这种不属于时间选择器呀，用两个RecyclerView 不就搞定了吗
