### ISSUE TITLE
NumberPicker似乎上下Padding是不一样的。造成无法正常水平居中

### ISSUE THREAD

**Issue by liyuhaolol** [loperSeven/DateTimePicker#89]
![WX20230802-114226@2x](https://github.com/loper7/DateTimePicker/assets/16422963/2c2517ef-3720-44e3-b9c1-502d869d87e3)
- 图里可以明确看出来NumberPicker的上下padding明显不一样，造成选择盘并不居中。
- 图里也截出了代码，和预览，选择器的中间年份，无论如何也无法跟右侧的TextView里的文字对齐，我已经尽量查找所有np里的自定义属性，完全没有任何东西可以控制这个问题。
- 所以我想知道，这算是BUG呢？还是我哪里属性没有找到？

**Comment by loper7** [comment]
不要固定numberpicker的高度，非要设置高度，可以用np_height
