### ISSUE TITLE
一个小的需求建议

### ISSUE THREAD

**Issue by StefanTimber** [loperSeven/DateTimePicker#9]
很好用的库，感谢！提一个小需求：

能否自定义时间间隔？比如以10分钟为单位去选择时间，分钟的滚轮则显示：00/10/20/30/40/50

**Comment by loperSeven** [comment]
> 很好用的库，感谢！提一个小需求：
> 
> 能否自定义时间间隔？比如以10分钟为单位去选择时间，分钟的滚轮则显示：00/10/20/30/40/50

最近项目上线比较忙，可能没有时间来处理，不过这需求应该不难，DateTimePicker 目前是UI和逻辑完全分开的，你可以试试更改DateTimeController.kt的代码来实现你的需求

**Comment by StefanTimber** [comment]
好的，我自己研究下吧
祝新年快乐~~
