### ISSUE TITLE
下载不下来

### ISSUE THREAD

**Issue by Atraceofviciss** [loperSeven/DateTimePicker#90]
问题：
我在项目中，根据提供的配置，配置了 maven { url "https://jitpack.io" } 
以及 app的implementation 'com.github.loperSeven:DateTimePicker:0.6.3'，
但是在使用gradle加载时，总是不能下载下来，

需求：
这个项目能否提供jar 或者 arr,为项目提供离线版本

**Comment by loper7** [comment]
可以下载代码，以module方式导入项目，这样还方便修改
