### ISSUE TITLE
java版本怎么使用

### ISSUE THREAD

**Issue by xiaoniu667** [loperSeven/DateTimePicker#91]

**Comment by xiaoniu667** [comment]
var dialog = CardDatePickerDialog.builder(context)
                .setTitle("DATE&TIME PICKER")
                .setDisplayType(displayList)
                .setBackGroundModel(model)
//                .setBackGroundModel(if(isDark) R.drawable.shape_bg_dialog_dark else R.drawable.shape_bg_dialog_light)
                .showBackNow(checkBackNow.isChecked)
                .setMaxTime(maxDate)
                .setPickerLayout(pickerLayout)
                .setMinTime(minDate)
                .setDefaultTime(defaultDate)
                .setTouchHideable(true)
                .setChooseDateModel(DateTimeConfig.DATE_LUNAR)
                .setWrapSelectorWheel(false)
                .setThemeColor(if (model == R.drawable.shape_bg_dialog_custom) Color.parseColor("#FF8000") else 0)
//                .setAssistColor(Color.parseColor("#DDFFFFFF"))
//                .setDividerColor(Color.parseColor("#222222"))
                .showDateLabel(checkUnitLabel.isChecked)
                .showFocusDateInfo(checkDateInfo.isChecked)
                .setOnChoose("选择") {
                    btnCardDialogShow.text = "${
                        StringUtils.conversionTime(
                            it,
                            "yyyy-MM-dd HH:mm:ss"
                        )
                    }    ${StringUtils.getWeek(it)}"
                }
                .setOnCancel("关闭") {
                }.build()
            dialog.show()
            //重点 需要在dialog show 方法后
            //得到 BottomSheetDialog 实体，设置其 isHideable 为 fasle
            (dialog as BottomSheetDialog).behavior.isHideable = false

**Comment by loper7** [comment]
不太明白你遇到的问题是什么
