### ISSUE TITLE
希望作者能将本库迁移发布到MavenCentral

### ISSUE THREAD

**Issue by liyuhaolol** [loperSeven/DateTimePicker#96]
- 因为尚不知道是AndroidStudio的更新，还是JitPack.io官方更新导致。目前AS引用JitPack的库，将无法引用其源码。造成引用本库以后，点击看到的都是反编译后的代码。很影响代码阅读。情况如下图所示：
![error](https://github.com/loper7/DateTimePicker/assets/16422963/1aae2cfb-83d6-453d-a5b7-c76ac73832fa)
- 这个问题已经持续了至少6个月了，JitPack官方对这件事的反应极其消极。根本不打算修正这个问题，目前看起来是JitPack云编译生成的moudle文件内的文件名生成错误导致的。但是官方就很摆。我这看到的很多作者已经选择放弃JitPack平台，选择将库迁移到MavenCentral上面。且不说MavenCentral算是AS开发默认的一个仓库，更重要的是可以纠正无法查看库源码的问题。
- 我知道第一次通过Central Portal发布库的步骤远比无脑JitPack云编译要来的繁琐，但是后续更新就很无脑一句命令的问题。所以希望作者可以慎重考虑下我提出的这个请求。

- 相关链接
- [Maven Central官网](https://central.sonatype.com/) 推荐用github登录可以自动授权groupId
- [Sonatype Central Portal Publisher](https://gitlab.com/thebugmc/sonatype-central-portal-publisher) 支持Android Lib发布的三方Central Portal 发布工具,个人推荐。因为Sonatype和Google目前均没有Gradle官方直接办法进行AndroidLib发布。因为Sonatype今年2月刚重构了上传系统。整个API全是新的。

**Comment by loper7** [comment]
[抱拳] 会考虑的，我其他库有使用maven，这个是因为一开始就用的jitpack
