### ISSUE TITLE
java版本怎么使用

### ISSUE THREAD

**Issue by AlanPaine** [loperSeven/DateTimePicker#98]
![Uploading image.p
![image](https://github.com/loper7/DateTimePicker/assets/106868933/3819e3c6-242f-4567-82d2-d77dba8ea7bb)
ng…]()

**Comment by AlanPaine** [comment]
![image](https://github.com/loper7/DateTimePicker/assets/106868933/37cf959c-18c4-4f06-9cc7-352ba52962c1)

**Comment by AlanPaine** [comment]
![image](https://github.com/loper7/DateTimePicker/assets/106868933/b0b9147c-9bd0-4926-be7e-63c82e13473e)

**Comment by loper7** [comment]
参考 [wiki](https://github.com/loper7/DateTimePicker/wiki/CardDatePickerDialog-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)
