### ISSUE TITLE
自定义布局时间戳问题

### ISSUE THREAD

**Issue by final00000000** [loperSeven/DateTimePicker#99]
引入了最新的版本 然后自定义了布局  只有小时和分钟；
返回的时间戳也是只有小时和分钟 如何返回全部的时间戳？ 有遇到过的吗

**Comment by loper7** [comment]
方便的话贴一下你的使用方式

**Comment by final00000000** [comment]
通过Demo演示
```
主页返回数据
```
![image](https://github.com/user-attachments/assets/3e22848f-0de9-4faf-9247-fccf77d48c94)

```
XML
```
![image](https://github.com/user-attachments/assets/b60b5e45-2060-429b-bd8e-369f48db140e)

```
xml 引入的自定义布局 只有小时分钟 其他的给注释掉了
```
![image](https://github.com/user-attachments/assets/b5195cd8-e686-4ae9-b6b9-f0025fb59037)

**Comment by loper7** [comment]
![image](https://github.com/user-attachments/assets/ad564747-4419-4970-8390-e62faee3f69e)
同步数据的时候确实是这个逻辑，如果想要完整的时间戳，可以创建一个当前时间的calendar，把时分擦除，然后加上选择器选择的时间戳

**Comment by loper7** [comment]
这个后续会考虑优化
